### ISSUE TITLE
Can not program nRF52832 by pyOCD

### ISSUE THREAD

**Issue by iotvietmember** [mbedmicro/pyOCD#334] opened 2017-10-09 17:14 UTC
Hi all,

I have a development board that has Nordic nRF52832 SoC and CMSIS-DAP Interface.

I tried to use pyocd-flashtool to program for nrf52832 but the tool raise an error as the below image.

![capture](https://user-images.githubusercontent.com/15735613/31349999-a9ac4a24-ad4f-11e7-949a-5ac9e258cfea.PNG)

Thanks

**Comment by flit** [comment] 2018-06-18 16:59
@iotvietmember Do you still see this issue with the latest version of pyOCD at the HEAD of master? If so, could you send the hex file you are trying to program? Specifically, I'm wondering if the hex file attempts to program the UICR.

**Comment by henrikbrixandersen** [comment] 2018-11-05 19:58
Does pyOCD support programming/erasing the UICR?

**Comment by flit** [comment] 2019-01-26 19:53
The UICR region has been added to the nRF targets, but it wasn't present at the time this bug was created. Programming the UICR works, since it uses the same procedure as normal flash. But I'm not sure if erasing it works as that requires use of a different register. Chip erase will erase the UICR though.

**Comment by flit** [comment] 2019-02-02 00:41
Closing this issue since the failing hex file is not available. If the problem is seen again and you can provide the information to reproduce it, please reopen this issue.

**Closed by flit** 2019-02-02 00:41 UTC
Labels: backlog
