### ISSUE TITLE
Flashing Cypress device causes error

### ISSUE THREAD

**Issue by thegecko** [mbedmicro/pyOCD#713] opened 2019-08-14 09:13 UTC
OS: Mac OS 10.14.5
Mbed: 5.13.1
Compiler: GCC or AC6.11
pyOCD: 0.21.0
Target: Cypress PSoC6 WiFi BT Kit

Flashing the Cypress target above with a standard blinky example causes an error `'CY8C6xxA' object has no attribute 'options'`

e.g:

```
> ./pyocd flash --uid 190100008b131b14028b131b00000000000000002e127069 --target cy8c6xxA --erase=chip /Users/bob/Mbed Programs/mbed-os-example-blinky/BUILD/CY8CPROTO_062_4343W/GCC_ARM/mbed-os-example-blinky.hex

0001343:CRITICAL:__main__:uncaught exception: 'CY8C6xxA' object has no attribute 'options'
Traceback (most recent call last):
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/__main__.py", line 338, in run
    self._COMMANDS[self._args.cmd](self)
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/__main__.py", line 468, in do_flash
    with session:
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/core/session.py", line 287, in __enter__
    self.open()
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/core/session.py", line 367, in open
    self._board.init()
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/board/board.py", line 83, in init
    self.target.init()
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/core/coresight_target.py", line 158, in init
    seq.invoke()
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/utility/sequencer.py", line 201, in invoke
    resultSequence = call()
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/target/builtin/target_CY8C6xxA.py", line 412, in create_cy8c6xx7_core
    core0 = CortexM_CY8C6xxA(self, self.aps[1], self.memory_map, 0)
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/coresight/cortex_m.py", line 409, in __init__
    Target.__init__(self, session, memoryMap)
  File "/Users/thegecko/mbed-studio-tools/python/lib/python2.7/site-packages/pyocd/core/target.py", line 98, in __init__
    self.halt_on_connect = session.options.get('halt_on_connect')
AttributeError: 'CY8C6xxA' object has no attribute 'options'
```

**Comment by flit** [comment] 2019-08-17 19:03
Duplicate of #680. Fixed on master.

**Closed by flit** 2019-08-17 19:03 UTC
Labels: duplicate
