### ISSUE TITLE
pyocd-flashtool doesn't work at all with RPiv3

### ISSUE THREAD

**Issue by jupe** [mbedmicro/pyOCD#270] opened 2016-12-09 12:40 UTC
`pyocd-flashtool` doesn't list any devices I've connected. Instead `mbedls` works fine. pyocd was clean clone from head of master and installed with command `python setup.py develop` .

This might be similar issue than #241, and there was mention that #262 should fix the problem, but I've still problem.

What I used:
```
~/pyOCD/ $ git rev-parse HEAD
48610ba219264d5306fa68bef2cd4ca89ef82067
$ uname -a
Linux raspberrypi 4.4.26-v7+ #915 SMP Thu Oct 20 17:08:44 BST 2016 armv7l GNU/Linux`
```

What happens:

```
~/pyOCD/ $ pyocd-flashtool -l -d debug
DEBUG:root:Exception getting product string: The device has no langid
DEBUG:root:Exception getting product string: The device has no langid
DEBUG:root:Exception getting product string: The device has no langid
DEBUG:root:Exception getting product string: The device has no langid
DEBUG:root:Exception getting product string: The device has no langid

$ mbedls
mbedls -j
[
    {
        "daplink_auto_reset": "0",
        "daplink_automation_allowed": "0",
        "daplink_daplink_mode": "Interface",
        "daplink_git_sha": "eab079b8a1326f0a3647e3df33cf5dda13994a1f",
        "daplink_hic_id": "97969900",
        "daplink_interface_crc": "0xdd5ee0ec",
        "daplink_interface_version": "0242",
        "daplink_local_mods": "0",
        "daplink_unique_id": "0240000034544e45004b00018aa9001d2011000097969900",
        "daplink_usb_interfaces": "MSD, CDC, HID",
        "daplink_version": "0242",
        "mount_point": "/mnt/platform-3f980000_usb-usb-0_1_3_3_1_0-scsi-0_0_0_0",
        "platform_name": "K64F",
        "platform_name_unique": "K64F[0]",
        "serial_port": "/dev/ttyACM2",
        "target_id": "0240000034544e45004b00018aa9001d2011000097969900",
        "target_id_mbed_htm": "0240000034544e45004b00018aa9001d2011000097969900",
        "target_id_usb_id": "0240000034544e45004b00018aa9001d2011000097969900"
 },
 ...
....
```

**Comment by jupe** [comment] 2016-12-09 12:42
same happens with `pyocd-gdbserver`:

```
$ pyocd-gdbserver -l
No available boards are connected
```

**Comment by jupe** [comment] 2016-12-09 12:44
verified that master works fine with windows:
```
C:\git\github\mbedmicro\pyOCD>pyocd-flashtool -l
0 => FRDM-K64F [k64f] boardId => 0240000029164e4500400012706e0005f301000097969900
```

**Comment by jupe** [comment] 2016-12-09 12:58
linux (virtualbox - ubuntu 16.04) seems to be also broken:

```
$ pyocd-flashtool -l -d debug
DEBUG:root:Exception getting product string: The device has no langid
DEBUG:root:Exception getting product string: The device has no langid
DEBUG:root:Exception getting product string: The device has no langid
No available boards are connected

$ mbedls -j
[
    {
        "daplink_auto_reset": "0", 
        "daplink_automation_allowed": "0", 
```

**Comment by jupe** [comment] 2016-12-12 10:44
running with `sudo` in linux seems to work. So issue here is just lack of documentation. Please add some mention that this needs `sudo` access when running in linux and introduction how to run without `sudo` .

**Comment by 0xc0170** [comment] 2016-12-13 08:52
Referencing #267 (same similar problem, less information though, duplicated).

**Comment by c1728p9** [comment] 2017-02-11 19:39
Closing this issue since it is a duplicate of #267. Please re-open if this is not the case.

**Closed by c1728p9** 2017-02-11 19:39 UTC
Labels: type: bug
