### ISSUE TITLE
How to improve the pyocd flash download speed?

### ISSUE THREAD

**Issue by ECNU3D** [mbedmicro/pyOCD#23] opened 2014-04-29 12:48 UTC
Hi all, I'm work on the pyocd flash download issue. I compare the download speed of CMSIS DAP with keil and pyocd:
1. When you download a 500KB bin file to the mbed lpc1768 => 
   keil -> cmsis_dap debugger -> target lpc1768 spends about 50s
   pyocd(window&linux) -> cmsis_dap debugger -> target lpc1768 spends about 110s   
2. With the help of some python performance  analysis tool, we can find that pyocd spend most of its time on usb write&read function
   Whole time: 109.656s
   Usb read&write: 45.946+14.38+23.016+20.969 = 104.311, so pyocd spends more than 95% of its run time on USB read/write function.
3.       After use time cmd to briefly analysis the pyocd run time:
   User 2.14
   System 0.72
   Real 102.44
   From the analysis above we can see that most of time wasn’t spent in user mode or kernel mode, so most time consumption should lie in IO wait time.

According to the analysis, I’ve changed the behavior of dapTransferBlock, and divided the write and read usb endpoint into two thread to avoid some IO wait time. However, only 10% speed enhancement is gained from this new feature. So do you have any clue about the low download speed of PyOCD?

**Comment by c1728p9** [comment] 2015-02-22 23:44
I have two pull requests up to increase flash programming speeds if anyone is interested in trying them.

The first pull request increases the data transfer rate by allowing packets to be queued, and by creating a dedicated reader thread for pyusb.  Testing on my local machine this brings data rates from ~25KB/s to ~45KB/s.
https://github.com/mbedmicro/pyOCD/pull/99

The second pull request updates the flash programming code to only program pages as necessary.  Mass erase programming will skip pages that would have been programmed to 0xFF (since they will already have been erased).  Sector erase programming skips pages that are already the same.
https://github.com/mbedmicro/pyOCD/pull/104

**Comment by Timmmm** [comment] 2016-05-26 12:36
These data rates are embarassing low for USB (even 'full speed'). nRF51 programming is about 10 times slower with `pyocd-flashtool` than `nrfjprog`. If we are allowed to change the USB interface it would be better to use a bulk endpoint.

I assume HID was used because you don't need to write a kernel driver? If so a better alternative is to set up the device as a [WinUSB Device](https://msdn.microsoft.com/en-gb/library/windows/hardware/hh450799%28v=vs.85%29.aspx). Basically you add a few USB string descriptors and Windows will automatically install your device using the WinUSB driver (works on Windows 7 and later). Then you can use `libusb` to access it. I'm not sure how it would work on OSX but it could fall back to HID if necessary.

I have code to turn mBed boards into WinUSB devices if people are interested. Is the USB CMSIS-DAP actually a standard or have the mBed people just made it up?

**Comment by sg-** [comment] 2016-05-28 03:52
@Timmmm What boards are you using and which version of firmware. There have been quite a few improvements and still room for a few more I think.

**Comment by Timmmm** [comment] 2016-05-28 14:44
Using nRF51-DK, latest firmware from Nordic. There's an mBed/CMSIS-DAP version and a JLink version (go [here](https://www.nordicsemi.com/eng/Products/nRF51-DK), click Downloads then scroll down to nRF5x-OB-JLink/mBed-IF). Using the mBed one with `pyocd-flashtool` takes about ... 15 seconds maybe to flash the chip. JLink takes about 2.

Using chip erase for both because Nordic say it is faster.

**Comment by shangdawei** [comment] 2016-11-04 06:19
@Timmmm You said, "I have code to turn mBed boards into WinUSB devices if people are interested. "

I am interested.

can you tell me how to turn to Winusb device ?

To modify firmware, uses Winusb descriptor ? Or Modify Host software ?

Thank you!

**Comment by Timmmm** [comment] 2016-11-04 22:42
It's a [work in progress](https://developer.mbed.org/users/Timmmm/code/UsbKnob/), but it does work. The relevant bits are in `WinUSBDevice.cpp/h`. Check out the `Readme.md` for lots of wordy unfinished information. Also [this excellent wiki](https://github.com/pbatard/libwdi/wiki/WCID-Devices) is well worth reading.

**Comment by Timmmm** [comment] 2016-11-04 22:47
By the way I should say, that code just reads an analogue in every 100 ms and sends it over an interrupt endpoint. I have code to connect to it and read it. It's not on the web anywhere so I'll just paste it here (sorry for the length!).

The device is found via its interface GUID, rather than vendor ID/product ID. The WinUSB driver is automatically installed when you plug it in.

# `Device.h`

```
#pragma once

#include <initguid.h>
#include <winusb.h>
#include <usb.h>
#include <Windows.h>

#include <vector>
#include <string>

class UsbKnob
{
public:
	UsbKnob();

	bool Open(std::wstring path);
	void Close();

	// Query the device speed. Returns 0 for failure, or LowSpeed (1), FullSpeed (2), or HighSpeed (3).
	UCHAR QuerySpeed();

	// This blocks forever until a value is sent. It returns 0 on success.
	int ReadValue(double& value);

private:
	UsbKnob(const UsbKnob&) = delete;
	UsbKnob& operator=(const UsbKnob&) = delete;
	

	HANDLE mDeviceHandle = INVALID_HANDLE_VALUE;
	WINUSB_INTERFACE_HANDLE mWinUsbInterfaceHandle = nullptr;

	UCHAR mPipeId = 0;

};

struct UsbKnobInfo
{
	std::wstring path;
};

std::vector<UsbKnobInfo> EnumerateKnobs();

// Device Interface GUID.
// Used by all WinUsb devices that this application talks to.
// Must match "DeviceInterfaceGUIDs" registry value obtained via USB.
DEFINE_GUID(GUID_DEVINTERFACE_Iso, 0xa451588c, 0x7230, 0x4076, 0x84, 0x56, 0x9e, 0x54, 0x41, 0x65, 0xe9, 0x0c);
```

# `Device.cpp`

```
#include "stdafx.h"

#include "Device.h"

#include <SetupAPI.h>


#include <tchar.h>
#include <strsafe.h>
#include <fstream>


UsbKnob::UsbKnob()
{
}

bool UsbKnob::Open(std::wstring path)
{
	Close();

	mDeviceHandle = CreateFile(path.c_str(),
		GENERIC_WRITE | GENERIC_READ,
		FILE_SHARE_WRITE | FILE_SHARE_READ,
		NULL,
		OPEN_EXISTING,
		FILE_ATTRIBUTE_NORMAL | FILE_FLAG_OVERLAPPED,
		NULL);

	HRESULT hr;

	if (mDeviceHandle == INVALID_HANDLE_VALUE)
	{
		hr = HRESULT_FROM_WIN32(GetLastError());
		return false;
	}

	BOOL bResult = WinUsb_Initialize(mDeviceHandle, &mWinUsbInterfaceHandle) != 0;

	if (bResult == FALSE)
	{
		hr = HRESULT_FROM_WIN32(GetLastError());
		Close();
		return false;
	}

	// Find the interrupt pipe.
	USB_INTERFACE_DESCRIPTOR usbInterface;

	bResult = WinUsb_QueryInterfaceSettings(mWinUsbInterfaceHandle,	0, &usbInterface);

	if (bResult == FALSE)
	{
		hr = HRESULT_FROM_WIN32(GetLastError());
		Close();
		return false;
	}

	for (UCHAR i = 0; i < usbInterface.bNumEndpoints; i++)
	{
		WINUSB_PIPE_INFORMATION_EX pipe;
		bResult = WinUsb_QueryPipeEx(mWinUsbInterfaceHandle, 0, i, &pipe);

		if (bResult == FALSE)
		{
			HRESULT hr = HRESULT_FROM_WIN32(GetLastError());
			Close();
			return false;
		}

		if ((pipe.PipeType == UsbdPipeTypeInterrupt) && USB_ENDPOINT_DIRECTION_IN(pipe.PipeId))
		{
			mPipeId = pipe.PipeId;
		}
	}

	return true;
}

void UsbKnob::Close()
{
	if (mWinUsbInterfaceHandle != nullptr)
	{
		WinUsb_Free(mWinUsbInterfaceHandle);
		mWinUsbInterfaceHandle = nullptr;
	}

	if (mDeviceHandle != INVALID_HANDLE_VALUE)
	{
		CloseHandle(mDeviceHandle);
		mDeviceHandle = INVALID_HANDLE_VALUE;
	}
}

UCHAR UsbKnob::QuerySpeed()
{
	if (mDeviceHandle == INVALID_HANDLE_VALUE)
	{
		return 0;
	}
	
	UCHAR deviceSpeed = 0;
	ULONG length = sizeof(UCHAR);
	BOOL bResult = WinUsb_QueryDeviceInformation(mDeviceHandle, DEVICE_SPEED, &length, &deviceSpeed);
	if (bResult == FALSE)
	{
		printf("Error getting device speed: %d.\n", GetLastError());
		return 0;
	}

	return deviceSpeed;
}

int UsbKnob::ReadValue(double& value)
{
	if (mWinUsbInterfaceHandle == nullptr)
		return -1;

	UCHAR buffer[1024];

	ULONG transferred = 0;

	BOOL bResult = WinUsb_ReadPipe(mWinUsbInterfaceHandle, mPipeId, buffer, sizeof(buffer), &transferred, nullptr);
	if (bResult == FALSE)
	{
		//		hr = HRESULT_FROM_WIN32(GetLastError());
		return HRESULT_FROM_WIN32(GetLastError());
	}

	printf("Transferred: %d\n", transferred);
	if (transferred == 4)
	{
		uint32_t t = buffer[0] +
			(buffer[1] << 8) +
			(buffer[2] << 16) +
			(buffer[3] << 24);
		value = t / double(0xFFFFFFFF);
		return 0;
	}

	return -1;
}

std::vector<UsbKnobInfo> EnumerateKnobs()
{
	PSP_DEVICE_INTERFACE_DETAIL_DATA detailData = NULL;
	
	std::vector<UsbKnobInfo> knobs;

	// Enumerate all devices exposing the interface
	HDEVINFO deviceInfoSet = SetupDiGetClassDevs(&GUID_DEVINTERFACE_Iso, NULL, NULL, DIGCF_PRESENT | DIGCF_DEVICEINTERFACE);

	if (deviceInfoSet == INVALID_HANDLE_VALUE)
	{
		// hr = HRESULT_FROM_WIN32(GetLastError());
		return knobs;
	}

	SP_DEVICE_INTERFACE_DATA interfaceData;
	interfaceData.cbSize = sizeof(SP_DEVICE_INTERFACE_DATA);

	// Get the first interface (index 0) in the result set
	for (int idx = 0;; ++idx)
	{
		BOOL bResult = SetupDiEnumDeviceInterfaces(deviceInfoSet, NULL, &GUID_DEVINTERFACE_Iso, idx, &interfaceData);
		if (bResult == FALSE)
		{
			if (GetLastError() == ERROR_NO_MORE_ITEMS)
				break;
			//		hr = HRESULT_FROM_WIN32(GetLastError());
			break;
		}

		// Get the size of the path string
		// We expect to get a failure with insufficient buffer
		ULONG requiredLength = 0;
		bResult = SetupDiGetDeviceInterfaceDetail(deviceInfoSet, &interfaceData, NULL, 0, &requiredLength, NULL);

		if (bResult == FALSE && GetLastError() != ERROR_INSUFFICIENT_BUFFER)
		{
			//		hr = HRESULT_FROM_WIN32(GetLastError());
			break;
		}

		// Allocate temporary space for SetupDi structure
		detailData = (PSP_DEVICE_INTERFACE_DETAIL_DATA)LocalAlloc(LMEM_FIXED, requiredLength);

		if (detailData == nullptr)
		{
//			hr = E_OUTOFMEMORY;
			break;
		}

		detailData->cbSize = sizeof(SP_DEVICE_INTERFACE_DETAIL_DATA);
		ULONG length = requiredLength;

		// Get the interface's path string
		bResult = SetupDiGetDeviceInterfaceDetail(deviceInfoSet, &interfaceData, detailData, length, &requiredLength, NULL);

		if (bResult == FALSE)
		{
//			hr = HRESULT_FROM_WIN32(GetLastError());
			LocalFree(detailData);
			break;
		}

		// SetupDiGetDeviceInterfaceDetail ensured DevicePath is NULL-terminated.
		UsbKnobInfo info;
		info.path = detailData->DevicePath;
		knobs.push_back(info);

		LocalFree(detailData);
	}
	SetupDiDestroyDeviceInfoList(deviceInfoSet);
	return knobs;
}

```

Use it in the obvious way, like this:

```
	std::vector<UsbKnobInfo> knobs = EnumerateKnobs();
	printf("Found %d knobs\r\n", knobs.size());

	if (knobs.size() != 1)
	{
		printf("Need 1 knob only.\r\n");
		return 1;
	}

	UsbKnob knob;
	if (!knob.Open(knobs[0].path))
	{
		printf("Couldn't open knob.\r\n");
		return 1;
	}

	for (;;)
	{
		double val = -1.0;
		int ret = knob.ReadValue(val);
		printf("Returned %d; Read value: %f\n", ret, val);
	}
```

Good luck!

**Comment by c1728p9** [comment] 2016-11-23 20:28
Hi @Timmmm, thanks for the information on WinUSB. This won't be able to replace CMSIS-DAP over HID at least for DAPLink, but may be possible as an alternative. Can WinUSB be used as part of a composite USB device (for example CDC + Mass storage + WinUSB), or does it apply to the whole device?

**Comment by flit** [comment] 2016-11-23 22:47
@c1728p9 I've been thinking about this, too, where we could add a USB bulk pipe as an alternative transport. DAPLink would default to HID. A vendor specific command could be used to switch the CMSIS-DAP command stream over to the bulk pipe. Or perhaps the bulk pipe is always enabled and simply used if detected in the configuration. I'd prefer to not move away from CMSIS-DAP commands since most CMSIS-DAP commands would benefit from the reduced latency.

Btw, libusb is available for macOS via homebrew, but I've never had success using it with the pyDAPAccess libusb backend.

**Comment by Timmmm** [comment] 2016-11-24 16:57
@c1728p9 According to the quick search I just did it can work with just one part of a composite device. I might see if I can modify the mBed CMSIS-DAP code to add a WinUSB interface.

**Comment by Timmmm** [comment] 2016-12-01 20:50
Well I bought a DAPlink (the DipDap; great name btw), but unfortunately it seems that [DAPlink doesn't support gcc](https://github.com/mbedmicro/DAPLink/issues/197) and you need a £3k Keil licence to compile it, so... good luck guys!

**Comment by kylemanna** [comment] 2016-12-01 23:48
I'd be interested in using such feature enhancements on Linux, is it possible to do them in a portable way?  I'm not familiar with WinUSB, but it doesn't sound portable.

**Comment by c1728p9** [comment] 2016-12-02 00:28
It's a bummer that you are blocked on this @Timmmm. Is there anything I can do to help you? If you are able to create the right USB descriptor for a composite device using WinUSB with mbed, I could probably pull it into DAPLink. Switching this codebase over to GCC is definitely something that needs to be done, but this is far out since it requires a lot of work. An attempt was made at this earlier this year, but because the version of RTX DAPLink uses doesn't have GCC support this couldn't be done.  Once RTX is updated then GCC support should be straight forward to add.

**Comment by Timmmm** [comment] 2016-12-02 09:27
@kylemanna: Don't worry, Linux isn't disadvantaged by using a WinUSB device. Maybe I should explain it just to be clear.

When you plug in a USB device it provides a description of its interfaces and what 'class' they are. There are standard classes, and a vendor-defined class. Normally, if you use the standard classes the OS will automatically install a driver for you. If you use a vendor class you have to do it manually (or get it into Microsoft's online driver database).

Because of the hassle of driver installation, many people chose to (ab)use the standard [HID](https://en.wikipedia.org/wiki/Human_interface_device) class for non-HID-related things. It was meant for things like keyboard and mice, but actually you can send arbitrary messages over it. This is what DAPlink currently does. The problem is that HID uses an [interrupt endpoint](http://www.beyondlogic.org/usbnutshell/usb4.shtml), which is very low latency, but also low bandwidth (coincidentally the kind of transport you want for keyboards and mice!).

DAPlink doesn't really care about latency, but bandwidth is more important, otherwise flashing takes ages. For that you should really use a bulk endpoint. That is the type used by USB memory sticks. It has much higher bandwidth. The LPC11U35 used on the DipDap has USB Full Speed (12 Mb/s) - USB High Speed (480 Mb/s) is relatively uncommon on microcontrollers. Anyway the maximym bandwidth of USB Full Speed using bulk transfers is around 1.2 MB/s which should be plenty for the tiny firmwares we want to transfer (see the USB 2 spec, table 5-9).

So ideally we want to use a vendor-class bulk endpoint with a `libusb`-compatible driver. As I said, this means we need to manually install a driver which is a bit of a pain. On Windows you can do that with [Zadig](http://zadig.akeo.ie/), or you make a `.inf` file and the user has to add it via the control panel. 'WinUSB devices' avoid this faff. They basically add some Microsoft-specific metadata (called WCID; Windows Compatible ID) to the USB descriptors that tell Windows to automatically install the WinUSB driver automatically for that device when you plug it in.

WinUSB is a generic user-space USB driver. If you access your USB device via WinUSB you can basically do any USB communication with it. There's really not much reason to use vendor-specific kernel-space USB drivers any more, unless you really need to do kernel-related things, for example if you're making a USB graphics card. If you're familiar with `libusb`, then WinUSB is basically Microsoft's version. In fact `libusb` can use WinUSB as a backend on Windows.

So in the ideal solution, DAPlink would contain the WCID data it needs to be identified as a WinUSB device, Windows would automatically install WinUSB as a driver for it (just for the bulk vendor interface; the HID interface will have to stick around for compatibility and will continue to use the native HID driver), and then pyOCD can use `libusb` to access it.

On Linux I *believe* you don't need to install any drivers to use `libusb` and you can just ignore the WCID data. You might need to set up some udev rules but Linux users are used to inconvenience so they won't mind! :-P

Sorry that turned into a bit of an essay!

**Comment by Timmmm** [comment] 2016-12-02 09:27
@c1728p9 Ok I'll see if I can make a rough edit to the code without compiling it.

**Comment by kylemanna** [comment] 2016-12-02 17:56
@Timmmm As long as something like libusb fills the void on Linux I'm happy and look forward to your work!  I was afraid alot of effort would be invested in building an interface that works fast on Windows then to have to write some more middleware to work on Linux and macOS.

As a timely note, have you see then: http://hackaday.com/2016/12/02/black-magic-probe-the-best-arm-jtag-debugger/ ?

It seems that they moved the gdb JTAG server to the debug probe which I would imagine would have even lower latency:

> But the BMP’s killer feature is that it runs a GDB server on the probe. It opens up a virtual serial port that you can connect to directly through GDB on your host computer. No need to hassle around with OpenOCD configurations, or to open up a second window to run [texane]’s marvelous st-util. Just run GDB, target extended-remote /dev/ttyACM0 and you’re debugging.

This could perhaps be an even simpler implementation assuming USB CDC driver in Windows/Linux/macOS is up to the for a different kind of for latency and throughput.

**Comment by Timmmm** [comment] 2016-12-06 09:44
Quick update: I've modified the USB descriptors so that it has an extra vendor-defined interface with bulk in and bulk out endpoints, but sadly I have discovered that the LPC11U35 only supports 10 endpoints (5 in and 5 out). Two are used for endpoint 0 (mandatory), two for USB Mass Storage Class (MSC), two for HID, and 4 for CDC (Serial). So there are none left for my custom interface. :-(

What do people think? Ditch HID? Is there anything apart from pyOCD that relies on it?

**Comment by c1728p9** [comment] 2016-12-06 14:59
Could you disable the HID endpoints for testing? It would be good to know if you can still use the other interfaces - MSD and CDC with a WinUSB device.

There are a couple programs which use HID. Offhand I know IAR Embedded Workbench and Keil uVision use CMSIS-DAP over hid. I think Atmel Studio does as well.

Even so, it might be possible with a secondary configuration descriptor or interface descriptor to achieve backwards compatibility.

**Comment by flit** [comment] 2016-12-06 17:39
We could have a CMSIS-DAP vendor specific command that triggers a reenumeration with the bulk endpoints enabled and HID disabled. Considerably more complicated, but it would work around the lack of endpoints.

**Comment by c1728p9** [comment] 2017-01-04 15:50
@Timmmm did you have any luck getting this working? Also, as another potential option data could be sent over the control endpoint, without the need for any dedicated endpoints. This would allow the code to bypass the 64 byte limit, and would also probably allow packets to be send faster than every 1ms.  What do you think?

**Comment by Timmmm** [comment] 2017-01-05 11:31
Sadly I got distracted by other projects but it is still on my todo list!

But yes actually using control transfers sounds like a great idea -
according to the USB 2 spec (Table 5-3) you can get up to about 15 MB/s
which should be plenty. Bit of a hack but it should also be much easier to
implement and means we can keep all the other interfaces.

**Comment by Timmmm** [comment] 2017-01-05 21:39
Wait scratch that. Table 5-3 is high speed; full speed is table 5-2 which
says control transfers go up to about 800 kB/s which is ok I guess. Bulk
and interrupt both go to about 1.2 MB/s. I guess HID imposes additional
limits.

**Comment by c1728p9** [comment] 2017-01-05 21:58
@Timmmm I think the limitation comes from the endpoint descriptors where the polling rate is specified. I believe the fastest polling rate is 1ms for full speed devices.

**Comment by Timmmm** [comment] 2017-01-06 22:33
I checked and `bInterval` is already set to 1 (poll every frame) for the HID endpoints.

**Comment by Timmmm** [comment] 2017-01-07 18:12
@c1728p9 Or do you mean that DAPlink doesn't queue packets? I guess if every packet is acked before the next one is sent you'd be limited to something like 32 kB/s which would explain why it is so slow.

**Comment by flit** [comment] 2017-01-07 19:19
Packet queuing is functional in DAPLink. We use it in pyOCD to improve download speeds quite a bit.

**Comment by c1728p9** [comment] 2017-01-08 17:19
@Timmmm I was trying to elaborate on the additional limits you referenced. You mentioned that interrupt transfers can go up to 1.2 MB/s. The limiting factor here though is the endpoint descriptor polling rate.

**Comment by flit** [comment] 2018-10-19 20:41
Closing this issue. High speed USB is one option for improving performance while sticking with HID. And in the coming months we will be supporting CMSIS-DAPv2 that uses bulk endpoints and WinUSB to enable userland access on Windows (see #431).

**Closed by flit** 2018-10-19 20:41 UTC
Labels: type: question

**Comment by raveslave** [comment] 2019-10-25 11:47
Are there any benchmarks / numbers available with the new CMSIS-DAPv2 bulk endpoint?
would be nice if we can get the same speeds as using a Segger J-Link

**Comment by flit** [comment] 2019-10-28 19:42
@raveslave The best numbers we have readily available are the results of the CI test runs. Unfortunately the results aren't public (the Jenkins server is on an Arm network). One thing that the results clearly show is that performance is highly variable depending on the MCU.

Here are the most recent speed test and flash test numbers for Windows 7 with Python 3.7:

```
------ Speed Test Performance ------
Target             RAM Read Speed   RAM Write Speed    ROM Read Speed

k82f25615            112.598 KB/s      141.921 KB/s      112.695 KB/s
kl82z7               105.811 KB/s      110.077 KB/s      105.868 KB/s
k22f                 112.889 KB/s      141.998 KB/s      112.671 KB/s
k64f                 112.453 KB/s      130.153 KB/s      112.369 KB/s
nrf51                 45.132 KB/s       45.257 KB/s       44.100 KB/s
nrf51                 48.471 KB/s       51.845 KB/s       48.337 KB/s

------ Test Rate ------
Target    Chip Erase          Page Erase          Page Erase (Same data)

k82f25615 26.265 KB/s         24.307 KB/s         102.434 KB/s        
kl82z7    32.684 KB/s         28.843 KB/s         95.112 KB/s         
k22f      30.619 KB/s         28.282 KB/s         101.423 KB/s        
k64f      26.931 KB/s         27.401 KB/s         103.404 KB/s        
nrf51     31.232 KB/s         17.657 KB/s         40.192 KB/s         
nrf51     35.908 KB/s         19.054 KB/s         45.779 KB/s         
```

The two nrf51 boards have different interface circuits, one high speed USB (DAPLink running on ATSAM3U2C, the nRF51-DK), the other full speed (DAPLink running on KL26Z, on a micro:bit). This shows how flash programming performance is dominated by the target's flash programming speed rather than USB.

From the logs, I can't tell for certain, but it should be using CMSIS-DAPv2 for these targets.

You can get numbers yourself by running `test/speed_test.py` and `test/flash_test.py`. Or just run `test/automated_test.py` and it will provide a report at the end with both.
